services:
  web-nginx:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: note_sondage_web
    env_file:
      - .env.web
    volumes:
      - ./nginx/templates-lan-http/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    restart: unless-stopped
    networks:
      note-sondage-public:
        aliases:
          - notesondage-web

networks:
  note-sondage-public:
    external: true
    name: note-sondage-public